### ISSUE TITLE
Use OCR datablocks properly in Cholesky.

### ISSUE THREAD

**Issue by alinas** [habanero-rice/cnc-ocr#1]
The Cholesky application needs to be changed to use one dimensional arrays in rems of doing the proper indexing (i*TILE+j). This will enable using OCR datablocks properly instead of the current malloc hack.

**Comment by DaoWen** [comment]
Closed by f9bf0e20374718dc8fae23cb80f53934770552b0. By [casting flat arrays into 2D arrays](http://cdecl.ridiculousfish.com/?q=cast+myFlatArray+into+pointer+to+array+2000+of+double) with a variable dimension we let the compiler do all the work. We can also re-put the datablocks gotten by s3ComputeStep since we now have access to the guids of step inputs (typedef'd as cncHandle_t).
