### ISSUE TITLE
Doesn't work with python 2.7?

### ISSUE THREAD

**Issue by chamibuddhika** [habanero-rice/cnc-ocr#13]
When I try to use cncocr_t I get this error.

"python: error while loading shared libraries: libpython2.6.so.1.0: cannot open shared object file: No such file or directory"

Looks like it needs python 2.6 in the path. But documentation states 2.7 (which is the version I have in my system) should be fine too. What's the catch here?

Thanks

**Comment by DaoWen** [comment]
Hello, and thanks for your interest in OCR / CnC!

It looks like something is misconfigured on your machine. We only distribute python source files (`*.py`) in the CnC-OCR toolchain, and since those can't be linked to a specific copy of the python library (e.g., `libpython2.6.so.1.0`), that makes me think it's a problem with your `python` binary. What happens when you try to run the `python` command directly? I expect you'll see the same error. Try searching the web for the error you reported above to find a way to fix your python installation.

I typically use the translator on a machine that only has Python 2.7 installed, so it definitely doesn't depend on 2.6. However, I've tried to keep it compatible with 2.6, and I even had it working with 2.5 at one point. You should be able to run the translator with either Python 2.6 or 2.7.

On another note, I'm currently in the process of moving this project to <a href="https://github.com/habanero-rice/cnc-framework">habanero-rice/cnc-framework</a>. That repo is the new home for our "Unified" CnC toolchain, which supports multiple runtime back-ends, including OCR and the Intel CnC runtime. The current version of the toolchain is <a href="https://xstack.exascale-tech.com/git/public?p=xstack.git;a=tree;f=hll/cnc;h=485d1c9661bc1e75c0a431e3350d8e075a07ad68;hb=refs/heads/apps/master">available on the apps/master branch in the xstack git repo</a>.

**Comment by DaoWen** [comment]
Based on our conversation at the CnC workshop earlier this month, I'm assuming this issue is resolved. Please use [habanero-rice/cnc-framework](https://github.com/habanero-rice/cnc-framework) to obtain the latest version of CnC-OCR, and use that project's issue tracker to report any future problems.
