### ISSUE TITLE
Port more benchmarks to CnC-OCR

### ISSUE THREAD

**Issue by alinas** [habanero-rice/cnc-ocr#2]
Available from other CnC implementations: Blackscholes, Heart Wall Tracking, Denoising (3D), Fluid registration, Smith-Waterman, Matrix Invert, etc.

**Comment by DaoWen** [comment]
I'm closing this enhancement request since this project has been rolled into the [Habanero CnC Framework project](habanero-rice/cnc-framework). We can open a duplicate request in the cnc-framework issue tracker if we find that the current set of CnC-OCR examples and apps is insufficient going forward.
